<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Acharya" failures="1" tests="10" name="Test" time="0.121" errors="0" timestamp="2023-07-22T10:59:02 IST">
  <testcase classname="TestNg_Programs.invocation_Count_Annotation" name="method" time="0.01"/>
  <testcase classname="TestNg_Programs.Enables_Annotation" name="setA" time="0.01"/>
  <testcase classname="TestNg_Programs.Dependends_On_Annotation" name="core" time="0.009"/>
  <testcase classname="TestNg_Programs.invocation_Count_Annotation" name="method" time="0.002"/>
  <testcase classname="TestNg_Programs.invocation_Count_Annotation" name="method" time="0.005"/>
  <testcase classname="TestNg_Programs.invocation_Count_Annotation" name="method" time="0.008"/>
  <testcase classname="TestNg_Programs.invocation_Count_Annotation" name="method" time="0.002"/>
  <testcase classname="TestNg_Programs.Dependends_On_Annotation" name="galaxy" time="0.023">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;lost&amp;gt; but was:&amp;lt;stii have&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<lost> but was:<stii have>
at TestNg_Programs.Dependends_On_Annotation.galaxy(Dependends_On_Annotation.java:30)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- galaxy -->
  <testcase classname="TestNg_Programs.Dependends_On_Annotation" name="itsDependMethod" time="0.002"/>
  <testcase classname="TestNg_Programs.Dependends_On_Annotation" name="solarSystem" time="0.0">
    <skipped/>
  </testcase> <!-- solarSystem -->
  <testcase classname="TestNg_Programs.Enables_Annotation" name="setB" time="0.0">
    <ignored/>
  </testcase> <!-- setB -->
</testsuite> <!-- Test -->
