<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Acharya" failures="1" tests="4" name="TestNg_Programs.Dependends_On_Annotation" time="0.034" errors="0" timestamp="2023-07-22T10:59:02 IST" skipped="1">
  <testcase classname="TestNg_Programs.Dependends_On_Annotation" name="galaxy" time="0.023">
    <failure message="expected:&lt;lost&gt; but was:&lt;stii have&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<lost> but was:<stii have>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at TestNg_Programs.Dependends_On_Annotation.galaxy(Dependends_On_Annotation.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- galaxy -->
  <testcase classname="TestNg_Programs.Dependends_On_Annotation" name="core" time="0.009"/>
  <testcase classname="TestNg_Programs.Dependends_On_Annotation" name="itsDependMethod" time="0.002"/>
  <testcase classname="TestNg_Programs.Dependends_On_Annotation" name="solarSystem" time="0.000">
    <skipped/>
  </testcase> <!-- solarSystem -->
</testsuite> <!-- TestNg_Programs.Dependends_On_Annotation -->
